name: hello world
on: workflow_dispatch
jobs:
  cmd:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
    #    run: echo "Welcome to Github-Actions" # execute single command
        run: |
          echo "this is first line"
          echo "this is second command"
          echo "This is third command"
