name: Context variable
on: push
jobs:
  cont-vars:
   runs-on: ubuntu-latest
   steps:
      - name: Context vars
        run: |
           echo "This workflow is trigerd by ${{ github.actor }}
           echo "The repo name is ${{ github.repository }}
           echo "The branch name is ${{ github.ref_name }}

      - name: Print all variable under github
        run: echo ${{ toJson(github) }}

      - name: Print environment variables
        run: echo "$GITHUB_SHA"
