name: Build & Deploy
on:
 pull_request:
   types: 
     - opened
     - synchronize
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building the app"
