name: input variables
on:
 workflow_dispatch:
   inputs:
     environment:
       description: "Please provide end to deploy"
       default: dev
       required: true
       type: choice
       options:
         - dev
         - testing
         - prod
     tags:
       description: Please provide deployment tags
       required: true
       
        
jobs:
  input-demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app in this env ${{ inputs.environment }}
        run: |
          echo "Deploying the code in this env ${{ inputs.environment }}"
          echo "this tag ${{ inputs.tags }} is going to deploy in this env ${{ inputs.environment }}"
